name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'


      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # - name: test
      #   run: |
      #     pwd
      #     ls -lh
      #     which pnpm
      #     pnpm --help

      - name: Install dependencies
        run: pnpm -C ./web install 

      - name: Build
        run: pnpm -C ./web build
