name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup pnpm
        uses: pnpm/setup-pnpm@v1

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Build
        run: pnpm run build
        working-directory: web

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: us15.me0.cn
          username: web1064
          password: 0kvzQ8ml
          local-dir: /web
          server-dir: /WEB/memos/
          timeout: 10000
